name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Start the Next.js application
      web:
        image: node:18
        ports:
          - 3000:3000
        options: --entrypoint /bin/sh
        # Commands to start your app
        runs:
          - name: Install dependencies
            run: |
              cd /github/workspace
              npm install
          - name: Start the application
            run: |
              npm run build
              npm start &
              # Wait for the server to start
              sleep 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'v22.6.0' 

    - name: Install Playwright dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test --reporter=html

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-test-results
        path: test-results
